import React, { useState } from 'react';
import { 
  Bookmark, 
  Trash2, 
  Compass, 
  GraduationCap, 
  Copy, 
  Check, 
  Clock, 
  ArrowRight
} from 'lucide-react';
import { UserProfileState, ProgramItem } from '../types';
import { PROGRAMS_DATA } from '../data/euEducationData';
import { CAREERS_DATA } from '../data/careersData';

interface SavedPathwayViewProps {
  profile: UserProfileState;
  savedProgramIds: string[];
  onToggleSaveProgram: (programId: string) => void;
  onNavigateToPrograms: () => void;
  onNavigateToCareers: () => void;
  onSelectProgram: (prog: ProgramItem) => void;
}

export const SavedPathwayView: React.FC<SavedPathwayViewProps> = ({
  profile,
  savedProgramIds,
  onToggleSaveProgram,
  onNavigateToPrograms,
  onNavigateToCareers,
  onSelectProgram,
}) => {
  const [copied, setCopied] = useState(false);
  const [completedSkillIds, setCompletedSkillIds] = useState<string[]>([]);

  const targetCareer = CAREERS_DATA.find((c) => c.id === profile.targetCareerId);
  const savedPrograms = PROGRAMS_DATA.filter((p) => savedProgramIds.includes(p.id));

  const toggleSkill = (id: string) => {
    setCompletedSkillIds((prev) =>
      prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]
    );
  };

  const handleCopyRoadmap = () => {
    const text = `Meetr European Roadmap:
Target Career: ${targetCareer ? targetCareer.title : 'General Tech'}
Education Stage: ${profile.educationLevel} (${profile.highSchoolPercentage}%)
Annual Budget: €${profile.annualBudgetEur.toLocaleString()}
Saved Programs:
${savedPrograms.map((p) => `- ${p.name} (${p.country}) at ${p.institutionName} (€${p.nonEuTuitionEurAnnual}/yr) - Deadline: ${p.applicationDeadline}`).join('\n')}
Generated by Meetr Platform.`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8">
      {/* Header */}
      <div className="mb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-blue-400">
            <Bookmark className="h-4 w-4" />
            <span>Personal Roadmap Engine</span>
          </div>
          <h1 className="mt-1 text-2xl font-bold tracking-tight text-white sm:text-3xl">
            My Customized European Education & Career Pathway
          </h1>
          <p className="mt-1 text-xs sm:text-sm text-slate-300">
            Your saved goal, milestone preparation timeline, and bookmarked accredited European degrees.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyRoadmap}
            className="flex items-center gap-1.5 rounded-xl border border-slate-800 bg-slate-900 px-3.5 py-2 text-xs font-semibold text-slate-300 hover:bg-slate-800 transition-colors"
          >
            {copied ? <Check className="h-4 w-4 text-emerald-400" /> : <Copy className="h-4 w-4" />}
            <span>{copied ? 'Copied to Clipboard' : 'Copy Summary'}</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Target Career & Skills (5 cols) */}
        <div className="space-y-6 lg:col-span-5">
          {/* Target Career Card */}
          <div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5 shadow-lg">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2">
                <Compass className="h-4 w-4 text-blue-400" />
                <h3 className="font-bold text-sm text-white">Target Career Goal</h3>
              </div>
              <button
                onClick={onNavigateToCareers}
                className="text-xs text-blue-400 hover:underline"
              >
                Change Goal
              </button>
            </div>

            {targetCareer ? (
              <div className="mt-4 space-y-3">
                <div>
                  <span className="rounded bg-blue-500/10 px-2 py-0.5 text-[10px] font-semibold text-blue-300 border border-blue-500/20">
                    {targetCareer.category}
                  </span>
                  <h4 className="mt-1 text-lg font-bold text-white">{targetCareer.title}</h4>
                  <p className="mt-1 text-xs text-slate-400">{targetCareer.description}</p>
                </div>

                <div className="rounded-xl bg-slate-950 p-3 border border-slate-800 text-xs">
                  <div className="text-[10px] uppercase font-bold text-slate-500">
                    European Market Compensation Benchmark
                  </div>
                  <div className="mt-1 flex items-baseline justify-between">
                    <span className="font-bold text-white text-sm">
                      €{targetCareer.salaryData.midEur.toLocaleString()} / year
                    </span>
                    {targetCareer.salaryData.midPln ? (
                      <span className="text-emerald-400 font-semibold">
                        ~{targetCareer.salaryData.midPln.toLocaleString()} PLN/mo
                      </span>
                    ) : (
                      <span className="text-emerald-400 font-semibold">
                        Mid-Level
                      </span>
                    )}
                  </div>
                </div>

                {/* Skills Checklist */}
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="font-bold text-xs text-white">Essential Skill Checklist:</span>
                    <span className="text-[10px] text-slate-400">
                      {completedSkillIds.length}/{targetCareer.requiredSkills.length} prepared
                    </span>
                  </div>

                  <div className="space-y-1.5">
                    {targetCareer.requiredSkills.map((sk) => {
                      const isDone = completedSkillIds.includes(sk.skillId);
                      return (
                        <div
                          key={sk.skillId}
                          onClick={() => toggleSkill(sk.skillId)}
                          className={`cursor-pointer flex items-center justify-between rounded-xl border p-2.5 text-xs transition-all ${
                            isDone
                              ? 'border-emerald-500/40 bg-emerald-950/20 text-emerald-200'
                              : 'border-slate-800 bg-slate-950/60 text-slate-300 hover:border-slate-700'
                          }`}
                        >
                          <div className="flex items-center gap-2">
                            <div
                              className={`flex h-4 w-4 items-center justify-center rounded border ${
                                isDone
                                  ? 'border-emerald-500 bg-emerald-500 text-black'
                                  : 'border-slate-600'
                              }`}
                            >
                              {isDone && <Check className="h-3 w-3" />}
                            </div>
                            <span className={isDone ? 'line-through opacity-75' : ''}>
                              {sk.name}
                            </span>
                          </div>
                          <span className="text-[9px] font-mono text-slate-500">
                            {sk.importance}
                          </span>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            ) : (
              <div className="mt-4 text-center py-6">
                <p className="text-xs text-slate-400">No career goal selected yet.</p>
                <button
                  onClick={onNavigateToCareers}
                  className="mt-3 rounded-xl bg-blue-600 px-4 py-2 text-xs font-semibold text-white hover:bg-blue-500"
                >
                  Explore Careers
                </button>
              </div>
            )}
          </div>

          {/* Action Milestones Timeline */}
          <div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5 shadow-lg space-y-4">
            <h3 className="font-bold text-sm text-white flex items-center gap-2 border-b border-slate-800 pb-3">
              <Clock className="h-4 w-4 text-emerald-400" />
              <span>International Student Milestone Roadmap</span>
            </h3>

            <div className="space-y-3 text-xs">
              <div className="flex items-start gap-3">
                <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-blue-600 text-[11px] font-bold text-white mt-0.5">
                  1
                </div>
                <div>
                  <h4 className="font-semibold text-white">Document Legalization & Apostille</h4>
                  <p className="text-[11px] text-slate-400">
                    Apostille high school diploma/Matura and obtain sworn translations to Polish.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-slate-800 text-[11px] font-bold text-slate-300 mt-0.5">
                  2
                </div>
                <div>
                  <h4 className="font-semibold text-white">University Portal Registration (IRK)</h4>
                  <p className="text-[11px] text-slate-400">
                    Submit application fee (85 PLN) and digital copies before June/July deadlines.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-slate-800 text-[11px] font-bold text-slate-300 mt-0.5">
                  3
                </div>
                <div>
                  <h4 className="font-semibold text-white">Consular Student Visa (D-11)</h4>
                  <p className="text-[11px] text-slate-400">
                    Book appointment via e-Konsulat, submit university acceptance letter, and prove ~800 PLN/mo subsistence funds.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-slate-800 text-[11px] font-bold text-slate-300 mt-0.5">
                  4
                </div>
                <div>
                  <h4 className="font-semibold text-white">Arrival in Poland (October Intake)</h4>
                  <p className="text-[11px] text-slate-400">
                    Academic year commences October 1st. Apply for statutory student card (50% train/bus discount).
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Bookmarked Programs (7 cols) */}
        <div className="space-y-4 lg:col-span-7">
          <div className="flex items-center justify-between">
            <h3 className="font-bold text-sm text-white flex items-center gap-2">
              <GraduationCap className="h-4 w-4 text-emerald-400" />
              <span>Saved University Programs ({savedPrograms.length})</span>
            </h3>
            <button
              onClick={onNavigateToPrograms}
              className="text-xs text-blue-400 hover:underline"
            >
              + Find More Programs
            </button>
          </div>

          {savedPrograms.length === 0 ? (
            <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-10 text-center">
              <GraduationCap className="mx-auto h-10 w-10 text-slate-600 mb-2" />
              <p className="text-xs text-slate-400">No university programs bookmarked yet.</p>
              <button
                onClick={onNavigateToPrograms}
                className="mt-3 rounded-xl bg-blue-600 px-4 py-2 text-xs font-semibold text-white hover:bg-blue-500"
              >
                Browse EU Degrees
              </button>
            </div>
          ) : (
            <div className="space-y-3">
              {savedPrograms.map((prog) => (
                <div
                  key={prog.id}
                  className="rounded-2xl border border-slate-800 bg-slate-900/80 p-4 shadow-sm space-y-3"
                >
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="rounded bg-blue-500/20 px-2 py-0.5 text-[10px] font-bold text-blue-300 border border-blue-500/30">
                          {prog.country}
                        </span>
                        <span className="rounded bg-slate-800 px-2 py-0.5 text-[10px] font-semibold text-slate-300">
                          {prog.institutionCity}
                        </span>
                        <span className="rounded bg-blue-500/10 px-2 py-0.5 text-[10px] font-semibold text-blue-300">
                          {prog.degreeLevel}
                        </span>
                      </div>
                      <h4 className="mt-1 font-bold text-white text-base leading-snug">
                        {prog.name}
                      </h4>
                      <div className="text-xs text-slate-400 font-medium">
                        {prog.institutionName}
                      </div>
                    </div>

                    <button
                      onClick={() => onToggleSaveProgram(prog.id)}
                      className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-800 hover:text-rose-400"
                      title="Remove from saved"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>

                  <div className="grid grid-cols-3 gap-2 rounded-xl bg-slate-950 p-3 text-xs border border-slate-800/80">
                    <div>
                      <span className="text-[10px] uppercase text-slate-500 font-semibold">Tuition</span>
                      <div className="font-bold text-emerald-400 mt-0.5">
                        €{prog.nonEuTuitionEurAnnual.toLocaleString()} / yr
                      </div>
                    </div>

                    <div>
                      <span className="text-[10px] uppercase text-slate-500 font-semibold">Duration</span>
                      <div className="font-bold text-white mt-0.5">
                        {prog.durationYears} yrs ({prog.ectsCredits} ECTS)
                      </div>
                    </div>

                    <div>
                      <span className="text-[10px] uppercase text-slate-500 font-semibold">Deadline</span>
                      <div className="font-bold text-amber-400 mt-0.5">
                        {prog.applicationDeadline}
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center justify-between pt-1">
                    <span className="text-[10px] text-slate-500 font-mono">
                      Register ID: {prog.openDatasetRegisterId}
                    </span>
                    <button
                      onClick={() => onSelectProgram(prog)}
                      className="text-xs text-blue-400 hover:underline font-semibold flex items-center gap-1"
                    >
                      <span>View Full Details</span>
                      <ArrowRight className="h-3 w-3" />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
