import React, { useState } from 'react';
import { 
  Bookmark, 
  Trash2, 
  Compass, 
  GraduationCap, 
  Copy, 
  Check, 
  Clock, 
  ArrowRight
} from 'lucide-react';
import { UserProfileState, ProgramItem } from '../types';
import { PROGRAMS_DATA } from '../data/euEducationData';
import { CAREERS_DATA } from '../data/careersData';

interface SavedPathwayViewProps {
  profile: UserProfileState;
  savedProgramIds: string[];
  onToggleSaveProgram: (programId: string) => void;
  onNavigateToPrograms: () => void;
  onNavigateToCareers: () => void;
  onSelectProgram: (prog: ProgramItem) => void;
}

export const SavedPathwayView: React.FC<SavedPathwayViewProps> = ({
  profile,
  savedProgramIds,
  onToggleSaveProgram,
  onNavigateToPrograms,
  onNavigateToCareers,
  onSelectProgram,
}) => {
  const [copied, setCopied] = useState(false);
  const [completedSkillIds, setCompletedSkillIds] = useState<string[]>([]);

  const targetCareer = CAREERS_DATA.find((c) => c.id === profile.targetCareerId);
  const savedPrograms = PROGRAMS_DATA.filter((p) => savedProgramIds.includes(p.id));

  const toggleSkill = (id: string) => {
    setCompletedSkillIds((prev) =>
      prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]
    );
  };

  const handleCopyRoadmap = () => {
    const text = `Meetr European Roadmap:
Target Career: ${targetCareer ? targetCareer.title : 'General Tech Exploration'}
Education Stage: ${profile.educationLevel} (${profile.highSchoolPercentage}%)
Annual Budget: €${profile.annualBudgetEur.toLocaleString()}
Saved Programs:
${savedPrograms.map((p) => `- ${p.name} (${p.country}) at ${p.institutionName} (€${p.nonEuTuitionEurAnnual}/yr) - Deadline: ${p.applicationDeadline}`).join('\n')}
Generated by Meetr Platform.`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8">
      {/* Header */}
      <div className="mb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 rounded-lg border-2 border-black bg-[#FFE600] px-3 py-1 text-xs font-mono font-black text-black shadow-[2px_2px_0px_0px_#000]">
            <Bookmark className="h-4 w-4 stroke-[2.5]" />
            <span>PERSONAL ROADMAP ENGINE</span>
          </div>
          <h1 className="mt-3 text-2xl sm:text-3xl lg:text-4xl font-black tracking-tight text-black font-display">
            My Customized European Pathway
          </h1>
          <p className="mt-1 text-xs sm:text-sm text-zinc-700 font-medium">
            Your saved goal, milestone preparation timeline, and bookmarked accredited European degrees.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyRoadmap}
            className="flex items-center gap-1.5 rounded-xl border-2 border-black bg-white hover:bg-[#FFE600] px-4 py-2.5 text-xs font-black text-black shadow-[3px_3px_0px_0px_#000] hover:translate-x-0.5 hover:translate-y-0.5 transition-all"
          >
            {copied ? <Check className="h-4 w-4 stroke-[3] text-black" /> : <Copy className="h-4 w-4 stroke-[2.5]" />}
            <span>{copied ? 'Copied to Clipboard' : 'Copy Summary'}</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Target Career & Skills (5 cols) */}
        <div className="space-y-6 lg:col-span-5">
          {/* Target Career Card */}
          <div className="rounded-2xl border-2 border-black bg-white p-5 shadow-[5px_5px_0px_0px_#000]">
            <div className="flex items-center justify-between border-b-2 border-black pb-3">
              <div className="flex items-center gap-2">
                <Compass className="h-5 w-5 text-black stroke-[2.5]" />
                <h3 className="font-black text-sm text-black font-display">Target Career Goal</h3>
              </div>
              <button
                onClick={onNavigateToCareers}
                className="text-xs font-black text-black bg-[#BAE6FD] px-2.5 py-1 rounded-lg border-2 border-black shadow-[1.5px_1.5px_0px_0px_#000] hover:bg-sky-300 transition-all"
              >
                Change Goal
              </button>
            </div>

            {targetCareer ? (
              <div className="mt-4 space-y-3">
                <div>
                  <span className="rounded-md border-2 border-black bg-[#BAE6FD] px-2 py-0.5 text-[10px] font-mono font-black text-black shadow-[1px_1px_0px_0px_#000]">
                    {targetCareer.category}
                  </span>
                  <h4 className="mt-2 text-lg font-black text-black font-display">{targetCareer.title}</h4>
                  <p className="mt-1 text-xs text-zinc-700 font-medium">{targetCareer.description}</p>
                </div>

                <div className="rounded-xl bg-[#FAF7F0] p-3 border-2 border-black text-xs shadow-[2px_2px_0px_0px_#000]">
                  <div className="text-[10px] uppercase font-black text-zinc-600 font-mono">
                    European Market Compensation Benchmark
                  </div>
                  <div className="mt-1 flex items-baseline justify-between font-mono">
                    <span className="font-black text-black text-sm">
                      €{targetCareer.salaryData.midEur.toLocaleString()} / year
                    </span>
                    {targetCareer.salaryData.midPln ? (
                      <span className="font-black text-black bg-[#A7F3D0] px-1.5 py-0.5 rounded border border-black shadow-[1px_1px_0px_0px_#000]">
                        ~{targetCareer.salaryData.midPln.toLocaleString()} PLN/mo
                      </span>
                    ) : (
                      <span className="font-black text-black bg-[#A7F3D0] px-1.5 py-0.5 rounded border border-black shadow-[1px_1px_0px_0px_#000]">
                        Mid-Level
                      </span>
                    )}
                  </div>
                </div>

                {/* Skills Checklist */}
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="font-black text-xs text-black uppercase font-mono">Essential Skill Checklist:</span>
                    <span className="text-[10px] font-mono font-black bg-[#FFE600] px-2 py-0.5 rounded border border-black shadow-[1px_1px_0px_0px_#000]">
                      {completedSkillIds.length}/{targetCareer.requiredSkills.length} prepared
                    </span>
                  </div>

                  <div className="space-y-2">
                    {targetCareer.requiredSkills.map((sk) => {
                      const isDone = completedSkillIds.includes(sk.skillId);
                      return (
                        <div
                          key={sk.skillId}
                          onClick={() => toggleSkill(sk.skillId)}
                          className={`cursor-pointer flex items-center justify-between rounded-xl border-2 border-black p-2.5 text-xs transition-all shadow-[2px_2px_0px_0px_#000] hover:translate-x-0.5 hover:translate-y-0.5 ${
                            isDone
                              ? 'bg-[#A7F3D0] text-black font-bold'
                              : 'bg-[#FAF7F0] text-black font-medium hover:bg-white'
                          }`}
                        >
                          <div className="flex items-center gap-2">
                            <div
                              className={`flex h-4 w-4 items-center justify-center rounded border-2 border-black ${
                                isDone
                                  ? 'bg-black text-white'
                                  : 'bg-white'
                              }`}
                            >
                              {isDone && <Check className="h-3 w-3 stroke-[3]" />}
                            </div>
                            <span className={isDone ? 'line-through opacity-80' : ''}>
                              {sk.name}
                            </span>
                          </div>
                          <span className="text-[9px] font-mono font-black text-zinc-600 uppercase">
                            {sk.importance}
                          </span>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </div>
            ) : (
              <div className="mt-4 text-center py-6">
                <p className="text-xs text-zinc-600 font-bold">No career goal selected yet (Exploration Mode).</p>
                <button
                  onClick={onNavigateToCareers}
                  className="mt-3 rounded-xl border-2 border-black bg-[#FFE600] px-4 py-2 text-xs font-black text-black shadow-[3px_3px_0px_0px_#000] hover:translate-x-0.5 hover:translate-y-0.5 transition-all"
                >
                  Explore Careers
                </button>
              </div>
            )}
          </div>

          {/* Action Milestones Timeline */}
          <div className="rounded-2xl border-2 border-black bg-white p-5 shadow-[5px_5px_0px_0px_#000] space-y-4">
            <h3 className="font-black text-sm text-black flex items-center gap-2 border-b-2 border-black pb-3 font-display">
              <Clock className="h-5 w-5 text-black stroke-[2.5]" />
              <span>International Student Milestone Roadmap</span>
            </h3>

            <div className="space-y-3.5 text-xs font-sans">
              <div className="flex items-start gap-3 rounded-xl border-2 border-black bg-[#FAF7F0] p-3 shadow-[2px_2px_0px_0px_#000]">
                <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg border-2 border-black bg-[#FFE600] text-xs font-black text-black shadow-[1.5px_1.5px_0px_0px_#000]">
                  1
                </div>
                <div>
                  <h4 className="font-black text-black font-display text-sm">Document Legalization & Apostille</h4>
                  <p className="mt-0.5 text-[11px] text-zinc-700 font-medium">
                    Apostille high school diploma/Matura and obtain sworn translations to target language.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3 rounded-xl border-2 border-black bg-[#FAF7F0] p-3 shadow-[2px_2px_0px_0px_#000]">
                <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg border-2 border-black bg-[#BAE6FD] text-xs font-black text-black shadow-[1.5px_1.5px_0px_0px_#000]">
                  2
                </div>
                <div>
                  <h4 className="font-black text-black font-display text-sm">University Portal Registration (IRK/Uni-Assist)</h4>
                  <p className="mt-0.5 text-[11px] text-zinc-700 font-medium">
                    Submit application fee and certified digital copies before national deadlines.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3 rounded-xl border-2 border-black bg-[#FAF7F0] p-3 shadow-[2px_2px_0px_0px_#000]">
                <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg border-2 border-black bg-[#A7F3D0] text-xs font-black text-black shadow-[1.5px_1.5px_0px_0px_#000]">
                  3
                </div>
                <div>
                  <h4 className="font-black text-black font-display text-sm">National Student Visa (Type D / Schengen)</h4>
                  <p className="mt-0.5 text-[11px] text-zinc-700 font-medium">
                    Book consulate appointment, submit acceptance letter, health insurance, and blocked account / living funds proof.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3 rounded-xl border-2 border-black bg-[#FAF7F0] p-3 shadow-[2px_2px_0px_0px_#000]">
                <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg border-2 border-black bg-[#FECDD3] text-xs font-black text-black shadow-[1.5px_1.5px_0px_0px_#000]">
                  4
                </div>
                <div>
                  <h4 className="font-black text-black font-display text-sm">Arrival in Europe (Autumn Intake)</h4>
                  <p className="mt-0.5 text-[11px] text-zinc-700 font-medium">
                    Semester commences Sept/Oct. Apply for residence card (Karta Pobytu / Aufenthaltskarte) and municipal registration.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Bookmarked Programs (7 cols) */}
        <div className="space-y-4 lg:col-span-7">
          <div className="flex items-center justify-between">
            <h3 className="font-black text-sm text-black flex items-center gap-2 font-display">
              <GraduationCap className="h-5 w-5 text-black stroke-[2.5]" />
              <span>Saved University Programs ({savedPrograms.length})</span>
            </h3>
            <button
              onClick={onNavigateToPrograms}
              className="text-xs font-black text-black bg-[#FFE600] px-3 py-1.5 rounded-lg border-2 border-black shadow-[2px_2px_0px_0px_#000] hover:translate-x-0.5 hover:translate-y-0.5 transition-all"
            >
              + Find More Programs
            </button>
          </div>

          {savedPrograms.length === 0 ? (
            <div className="rounded-2xl border-2 border-black bg-white p-10 text-center shadow-[5px_5px_0px_0px_#000]">
              <GraduationCap className="mx-auto h-12 w-12 text-black stroke-[2] mb-3" />
              <p className="text-xs text-zinc-700 font-bold">No university programs bookmarked yet.</p>
              <button
                onClick={onNavigateToPrograms}
                className="mt-4 rounded-xl border-2 border-black bg-[#FFE600] px-5 py-2.5 text-xs font-black text-black shadow-[3px_3px_0px_0px_#000] hover:translate-x-0.5 hover:translate-y-0.5 transition-all"
              >
                Browse European Degrees
              </button>
            </div>
          ) : (
            <div className="space-y-4">
              {savedPrograms.map((prog) => (
                <div
                  key={prog.id}
                  className="rounded-xl border-2 border-black bg-white p-5 shadow-[4px_4px_0px_0px_#000] space-y-3 hover:shadow-[6px_6px_0px_0px_#000] hover:-translate-x-0.5 hover:-translate-y-0.5 transition-all"
                >
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <div className="flex items-center gap-1.5 text-[10px] font-mono font-black">
                        <span className="rounded-md border-2 border-black bg-[#BAE6FD] px-2 py-0.5 text-black shadow-[1px_1px_0px_0px_#000]">
                          {prog.country}
                        </span>
                        <span className="rounded-md border-2 border-black bg-[#FEF08A] px-2 py-0.5 text-black shadow-[1px_1px_0px_0px_#000]">
                          {prog.institutionCity}
                        </span>
                        <span className="rounded-md border-2 border-black bg-[#FBCFE8] px-2 py-0.5 text-black shadow-[1px_1px_0px_0px_#000]">
                          {prog.degreeLevel}
                        </span>
                      </div>
                      <h4 className="mt-2.5 font-black text-black text-base leading-snug font-display">
                        {prog.name}
                      </h4>
                      <div className="text-xs text-zinc-700 font-bold">
                        {prog.institutionName}
                      </div>
                    </div>

                    <button
                      onClick={() => onToggleSaveProgram(prog.id)}
                      className="rounded-xl border-2 border-black bg-white p-2 text-black shadow-[2px_2px_0px_0px_#000] hover:bg-[#FECDD3] transition-all"
                      title="Remove from saved"
                    >
                      <Trash2 className="h-4 w-4 stroke-[2.5]" />
                    </button>
                  </div>

                  <div className="grid grid-cols-3 gap-2 rounded-xl bg-[#FAF7F0] p-3 text-xs border-2 border-black font-mono shadow-[2px_2px_0px_0px_#000]">
                    <div>
                      <span className="text-[10px] uppercase text-zinc-600 font-black">Tuition</span>
                      <div className="font-black text-black mt-0.5 text-sm">
                        €{prog.nonEuTuitionEurAnnual.toLocaleString()} / yr
                      </div>
                    </div>

                    <div>
                      <span className="text-[10px] uppercase text-zinc-600 font-black">Duration</span>
                      <div className="font-black text-black mt-0.5">
                        {prog.durationYears} yrs ({prog.ectsCredits} ECTS)
                      </div>
                    </div>

                    <div>
                      <span className="text-[10px] uppercase text-zinc-600 font-black">Deadline</span>
                      <div className="font-black text-black mt-0.5">
                        {prog.applicationDeadline}
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center justify-between pt-1">
                    <span className="text-[10px] text-zinc-600 font-mono font-bold">
                      Register ID: {prog.openDatasetRegisterId}
                    </span>
                    <button
                      onClick={() => onSelectProgram(prog)}
                      className="rounded-lg border-2 border-black bg-[#FFE600] px-3 py-1.5 text-xs font-black text-black shadow-[2px_2px_0px_0px_#000] hover:translate-x-0.5 hover:translate-y-0.5 transition-all flex items-center gap-1.5"
                    >
                      <span>View Full Details</span>
                      <ArrowRight className="h-3.5 w-3.5 stroke-[2.5]" />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
